### ISSUE TITLE
APP编译运行后所有数据返回空

### ISSUE THREAD

**Issue by Jackyhhh** [BaronZ88/MinimalistWeather#50]
![cbcd3ab02d177b1c09e1ee4c99832db](https://user-images.githubusercontent.com/34953618/103868803-5ef89300-5104-11eb-89bc-484f4877e98d.jpg)
![9092adacdd33ea46ca528d3a1f91740](https://user-images.githubusercontent.com/34953618/103868805-60c25680-5104-11eb-933a-6e48213f86a9.jpg)

**Comment by Jackyhhh** [comment]
/OAuthTokenProviderImpl: getTokenWithNotification failed [CONTEXT service_id=121 ]
    java.io.IOException: NetworkError

**Comment by Jackyhhh** [comment]
2021-01-07 16:22:19.685 23305-23351/? E/OAuthTokenProviderImpl: getTokenWithNotification failed [CONTEXT service_id=121 ]
    java.io.IOException: NetworkError
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2517)
        at android.accounts.AccountManager.access$700(AccountManager.java:162)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2368)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:107)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-01-07 16:22:19.689 23305-23346/? E/DomainFilterImpl: Error while reading domain filter from WHAPI [CONTEXT service_id=121 ]
    java.util.concurrent.ExecutionException: cook: UNAUTHENTICATED
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at aenz.get(:com.google.android.gms@204713037@20.47.13 (120400-344095733):0)
        at aesi.u(:com.google.android.gms@204713037@20.47.13 (120400-344095733):8)
        at aesi.c(:com.google.android.gms@204713037@20.47.13 (120400-344095733):6)
        at aesc.c(:com.google.android.gms@204713037@20.47.13 (120400-344095733):0)
        at com.google.android.gms.instantapps.routing.DomainFilterUpdateChimeraService.a(:com.google.android.gms@204713037@20.47.13 (120400-344095733):22)
        at afty.call(Unknown Source:4)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at tku.c(:com.google.android.gms@204713037@20.47.13 (120400-344095733):6)
        at tku.run(:com.google.android.gms@204713037@20.47.13 (120400-344095733):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tqr.run(:com.google.android.gms@204713037@20.47.13 (120400-344095733):0)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: cook: UNAUTHENTICATED
        at aenp.a(:com.google.android.gms@204713037@20.47.13 (120400-344095733):0)
        at aenx.call(:com.google.android.gms@204713037@20.47.13 (120400-344095733):0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at tku.c(:com.google.android.gms@204713037@20.47.13 (120400-344095733):6) 
        at tku.run(:com.google.android.gms@204713037@20.47.13 (120400-344095733):7) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at tqr.run(:com.google.android.gms@204713037@20.47.13 (120400-344095733):0) 
        at java.lang.Thread.run(Thread.java:919)
